# Generated by Django 3.0 on 2020-05-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Share', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharelink',
            name='to_file',
        ),
        migrations.AddField(
            model_name='sharelink',
            name='file_path',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
