# Generated by Django 3.0 on 2020-03-07 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Files_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='comment',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfile',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(max_length=5000, upload_to=''),
        ),
    ]
