# Generated by Django 3.0 on 2020-03-08 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Files_list', '0002_auto_20200307_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(max_length=255, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='userfile',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
    ]
