# Generated by Django 3.0 on 2020-03-08 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Files_list', '0003_auto_20200308_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdirectory',
            old_name='name',
            new_name='directory',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='name',
        ),
        migrations.AddField(
            model_name='userdirectory',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
