# Generated by Django 3.0 on 2020-03-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files_list', '0006_userfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdirectory',
            name='name',
            field=models.CharField(default='Folder', max_length=255),
        ),
    ]
