# Generated by Django 3.0 on 2020-03-26 14:49

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Files_list', '0008_auto_20200311_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='last_modification',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la dernière modification'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='directory',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(max_length=2000, storage=django.core.files.storage.FileSystemStorage(), upload_to=''),
        ),
    ]
