# Generated by Django 3.0 on 2020-05-21 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    # replaces = [('Files', '0001_initial'), ('Files', '0002_auto_20200307_1102'), ('Files', '0003_auto_20200308_1959'), ('Files', '0004_auto_20200308_2020'), ('Files', '0005_userfile_directory'), ('Files', '0006_userfile_name'), ('Files', '0007_userdirectory_name'), ('Files', '0008_auto_20200311_1333'), ('Files', '0009_auto_20200326_1449'), ('Files', '0010_userfile_size'), ('Files', '0011_FavoriteFile'), ('Files', '0012_auto_20200520_1700'), ('Files', '0013_auto_20200520_1701'), ('Files', '0014_RecentFile'), ('Files', '0015_delete_userfile')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('path', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='RecentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2000)),
                ('last_modification', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la dernière modification')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
