# Generated by Django 3.0 on 2020-04-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0009_auto_20200326_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
