# Generated by Django 3.0 on 2020-05-20 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Files', '0011_favoritefiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritefiles',
            name='file',
        ),
        migrations.AddField(
            model_name='favoritefiles',
            name='path',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='favoritefiles',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
