# Generated by Django 3.0 on 2020-05-20 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Files', '0013_auto_20200520_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2000)),
                ('last_modification', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la dernière modification')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
